source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end
gem 'rails'
gem 'pg'
gem 'puma'
gem 'sass-rails'
gem 'redis'
gem 'bcrypt'
group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :development do
  gem 'spring'
  gem 'spring-watcher-listen'
end
### END OF DEFAULT RAILS ###

# Emberjs
gem 'ember-rails'
gem 'jquery-rails'


# Testing
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'mocha'
end

# Api
gem 'active_model_serializers'